format:
  pdf:
    cap-location: top
    colorlinks: true
    csl: ./quarto/abnt.csl
    fig-pos: "H"
    fontsize: 12pt
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm
    include-in-header:
      - ./quarto/tex/packages.tex
      - ./quarto/tex/commands.tex
      - ./quarto/tex/settings.tex
    keep-tex: true
    link-citations: true
    pdf-engine: tectonic
  revealjs:
    footer: "Footer text"
    progress: true
    self-contained: true
    slide-level: 1
    slide-number: c/t
    theme: simple
    transition: slide
project:
  output-dir: ./quarto/output
  render:
    - project.qmd
    - thesis.qmd
    - slides.qmd
