[project]
name = "thesis"
version = "0.1.0"
description = "My economics bachelor's thesis (UFABC)"
authors = ["Pedro Mendes <pedrohrmendes@proton.me>"]
channels = ["conda-forge"]
platforms = ["linux-64"]
license = "GPL-3.0"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/phrmendes/thesis"

[tasks]
project = "quarto render project.qmd"
thesis = "quarto render thesis.qmd"
slides = "quarto render slides.qmd"
clean = "rm -rf .quarto output"

[dependencies]
python = ">=3.11,<3.12"
duckdb = ">=0.7.1,<0.8"
ipython = ">=8.21.0,<8.22"
jupyterlab = ">=4.1.0,<4.2"
jupyterlab-lsp = ">=5.0.3,<5.1"
jupyterlab_vim = ">=4.1.3,<4.2"
mapie = ">=0.8.2,<0.9"
neuralforecast = ">=1.6.4,<1.7"
numpy = ">=1.26.4,<1.27"
pandas = ">=2.2.0,<2.3"
pandoc = ">=3.1.1,<3.2"
pyarrow = ">=15.0.0,<15.1"
pydantic = ">=2.6.1,<2.7"
python-duckdb = ">=0.9.2,<0.10"
python-lsp-ruff = ">=2.0.2,<2.1"
python-lsp-server = ">=1.10.0,<1.11"
quarto = ">=1.3.450,<1.4"
requests = ">=2.31.0,<2.32"
ruff = ">=0.1.15,<0.2"
scikit-learn = ">=1.4.0,<1.5"
seaborn = ">=0.13.2,<0.14"
sqlalchemy = ">=2.0.25,<2.1"
statsmodels = ">=0.14.1,<0.15"
tectonic = ">=0.15.0,<0.16"
