target-version = "py311"
line-length = 88
indent-width = 4

exclude = [
  "__pycache__",
  ".direnv",
  ".git",
  ".ipynb_checkpoints",
  ".pixi",
  ".ruff_cache",
]

select = ["ALL"]

ignore = [
  "D100",   # missing docstring in public module
  "ARG001", # unused function argument
  "S603",   # subprocess call - check for execution of untrusted input
  "ANN101", # missing type annotation for self in method
]
